/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TempoIdentityRegistry } from "./TempoIdentityRegistry";
export type { TempoNameService } from "./TempoNameService";
export type { TempoReputationRegistry } from "./TempoReputationRegistry";
