/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TempoReputationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "appendResponse"
      | "feedbackCounts"
      | "feedbacks"
      | "getClients"
      | "getIdentityRegistry"
      | "getLastIndex"
      | "getResponseCount"
      | "getSummary"
      | "giveFeedback"
      | "identityRegistry"
      | "readAllFeedback"
      | "readFeedback"
      | "revokeFeedback"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeedbackRevoked"
      | "NewFeedback"
      | "ResponseAppended"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "appendResponse",
    values: [BigNumberish, AddressLike, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "feedbackCounts",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "feedbacks",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClients",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getIdentityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLastIndex",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getResponseCount",
    values: [BigNumberish, AddressLike, BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getSummary",
    values: [BigNumberish, AddressLike[], string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "giveFeedback",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      string,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "readAllFeedback",
    values: [BigNumberish, AddressLike[], string, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "readFeedback",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeFeedback",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "appendResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feedbackCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feedbacks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getClients", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getIdentityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResponseCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSummary", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "giveFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readAllFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeFeedback",
    data: BytesLike
  ): Result;
}

export namespace FeedbackRevokedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    clientAddress: AddressLike,
    feedbackIndex: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    clientAddress: string,
    feedbackIndex: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    clientAddress: string;
    feedbackIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewFeedbackEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    clientAddress: AddressLike,
    feedbackIndex: BigNumberish,
    value: BigNumberish,
    valueDecimals: BigNumberish,
    indexedTag1: string,
    tag1: string,
    tag2: string,
    endpoint: string,
    feedbackURI: string,
    feedbackHash: BytesLike
  ];
  export type OutputTuple = [
    agentId: bigint,
    clientAddress: string,
    feedbackIndex: bigint,
    value: bigint,
    valueDecimals: bigint,
    indexedTag1: string,
    tag1: string,
    tag2: string,
    endpoint: string,
    feedbackURI: string,
    feedbackHash: string
  ];
  export interface OutputObject {
    agentId: bigint;
    clientAddress: string;
    feedbackIndex: bigint;
    value: bigint;
    valueDecimals: bigint;
    indexedTag1: string;
    tag1: string;
    tag2: string;
    endpoint: string;
    feedbackURI: string;
    feedbackHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResponseAppendedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    clientAddress: AddressLike,
    feedbackIndex: BigNumberish,
    responder: AddressLike,
    responseURI: string,
    responseHash: BytesLike
  ];
  export type OutputTuple = [
    agentId: bigint,
    clientAddress: string,
    feedbackIndex: bigint,
    responder: string,
    responseURI: string,
    responseHash: string
  ];
  export interface OutputObject {
    agentId: bigint;
    clientAddress: string;
    feedbackIndex: bigint;
    responder: string;
    responseURI: string;
    responseHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TempoReputationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): TempoReputationRegistry;
  waitForDeployment(): Promise<this>;

  interface: TempoReputationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  appendResponse: TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      feedbackIndex: BigNumberish,
      responseURI: string,
      responseHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  feedbackCounts: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  feedbacks: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: BigNumberish],
    [
      [bigint, bigint, string, string, boolean] & {
        value: bigint;
        valueDecimals: bigint;
        tag1: string;
        tag2: string;
        isRevoked: boolean;
      }
    ],
    "view"
  >;

  getClients: TypedContractMethod<[agentId: BigNumberish], [string[]], "view">;

  getIdentityRegistry: TypedContractMethod<[], [string], "view">;

  getLastIndex: TypedContractMethod<
    [agentId: BigNumberish, clientAddress: AddressLike],
    [bigint],
    "view"
  >;

  getResponseCount: TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      feedbackIndex: BigNumberish,
      responders: AddressLike[]
    ],
    [bigint],
    "view"
  >;

  getSummary: TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddresses: AddressLike[],
      tag1: string,
      tag2: string
    ],
    [
      [bigint, bigint, bigint] & {
        count: bigint;
        summaryValue: bigint;
        summaryValueDecimals: bigint;
      }
    ],
    "view"
  >;

  giveFeedback: TypedContractMethod<
    [
      agentId: BigNumberish,
      value: BigNumberish,
      valueDecimals: BigNumberish,
      tag1: string,
      tag2: string,
      endpoint: string,
      feedbackURI: string,
      feedbackHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  readAllFeedback: TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddresses: AddressLike[],
      tag1: string,
      tag2: string,
      includeRevoked: boolean
    ],
    [
      [
        string[],
        bigint[],
        bigint[],
        bigint[],
        string[],
        string[],
        boolean[]
      ] & {
        clients: string[];
        feedbackIndexes: bigint[];
        values: bigint[];
        valueDecimals: bigint[];
        tag1s: string[];
        tag2s: string[];
        revokedStatuses: boolean[];
      }
    ],
    "view"
  >;

  readFeedback: TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      feedbackIndex: BigNumberish
    ],
    [
      [bigint, bigint, string, string, boolean] & {
        value: bigint;
        valueDecimals: bigint;
        tag1: string;
        tag2: string;
        isRevoked: boolean;
      }
    ],
    "view"
  >;

  revokeFeedback: TypedContractMethod<
    [agentId: BigNumberish, feedbackIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "appendResponse"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      feedbackIndex: BigNumberish,
      responseURI: string,
      responseHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feedbackCounts"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "feedbacks"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: BigNumberish],
    [
      [bigint, bigint, string, string, boolean] & {
        value: bigint;
        valueDecimals: bigint;
        tag1: string;
        tag2: string;
        isRevoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClients"
  ): TypedContractMethod<[agentId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getIdentityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLastIndex"
  ): TypedContractMethod<
    [agentId: BigNumberish, clientAddress: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResponseCount"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      feedbackIndex: BigNumberish,
      responders: AddressLike[]
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSummary"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddresses: AddressLike[],
      tag1: string,
      tag2: string
    ],
    [
      [bigint, bigint, bigint] & {
        count: bigint;
        summaryValue: bigint;
        summaryValueDecimals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "giveFeedback"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      value: BigNumberish,
      valueDecimals: BigNumberish,
      tag1: string,
      tag2: string,
      endpoint: string,
      feedbackURI: string,
      feedbackHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "readAllFeedback"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddresses: AddressLike[],
      tag1: string,
      tag2: string,
      includeRevoked: boolean
    ],
    [
      [
        string[],
        bigint[],
        bigint[],
        bigint[],
        string[],
        string[],
        boolean[]
      ] & {
        clients: string[];
        feedbackIndexes: bigint[];
        values: bigint[];
        valueDecimals: bigint[];
        tag1s: string[];
        tag2s: string[];
        revokedStatuses: boolean[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "readFeedback"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      feedbackIndex: BigNumberish
    ],
    [
      [bigint, bigint, string, string, boolean] & {
        value: bigint;
        valueDecimals: bigint;
        tag1: string;
        tag2: string;
        isRevoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeFeedback"
  ): TypedContractMethod<
    [agentId: BigNumberish, feedbackIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FeedbackRevoked"
  ): TypedContractEvent<
    FeedbackRevokedEvent.InputTuple,
    FeedbackRevokedEvent.OutputTuple,
    FeedbackRevokedEvent.OutputObject
  >;
  getEvent(
    key: "NewFeedback"
  ): TypedContractEvent<
    NewFeedbackEvent.InputTuple,
    NewFeedbackEvent.OutputTuple,
    NewFeedbackEvent.OutputObject
  >;
  getEvent(
    key: "ResponseAppended"
  ): TypedContractEvent<
    ResponseAppendedEvent.InputTuple,
    ResponseAppendedEvent.OutputTuple,
    ResponseAppendedEvent.OutputObject
  >;

  filters: {
    "FeedbackRevoked(uint256,address,uint64)": TypedContractEvent<
      FeedbackRevokedEvent.InputTuple,
      FeedbackRevokedEvent.OutputTuple,
      FeedbackRevokedEvent.OutputObject
    >;
    FeedbackRevoked: TypedContractEvent<
      FeedbackRevokedEvent.InputTuple,
      FeedbackRevokedEvent.OutputTuple,
      FeedbackRevokedEvent.OutputObject
    >;

    "NewFeedback(uint256,address,uint64,int128,uint8,string,string,string,string,string,bytes32)": TypedContractEvent<
      NewFeedbackEvent.InputTuple,
      NewFeedbackEvent.OutputTuple,
      NewFeedbackEvent.OutputObject
    >;
    NewFeedback: TypedContractEvent<
      NewFeedbackEvent.InputTuple,
      NewFeedbackEvent.OutputTuple,
      NewFeedbackEvent.OutputObject
    >;

    "ResponseAppended(uint256,address,uint64,address,string,bytes32)": TypedContractEvent<
      ResponseAppendedEvent.InputTuple,
      ResponseAppendedEvent.OutputTuple,
      ResponseAppendedEvent.OutputObject
    >;
    ResponseAppended: TypedContractEvent<
      ResponseAppendedEvent.InputTuple,
      ResponseAppendedEvent.OutputTuple,
      ResponseAppendedEvent.OutputObject
    >;
  };
}
