/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TempoNameServiceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentIdToName"
      | "identityRegistry"
      | "isNameAvailable"
      | "nameToAgentId"
      | "registerName"
      | "releaseName"
      | "resolveName"
      | "resolveOwner"
      | "reverseResolve"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "NameRegistered" | "NameReleased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentIdToName",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isNameAvailable",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "nameToAgentId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerName",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "releaseName", values: [string]): string;
  encodeFunctionData(functionFragment: "resolveName", values: [string]): string;
  encodeFunctionData(
    functionFragment: "resolveOwner",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "reverseResolve",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentIdToName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isNameAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nameToAgentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reverseResolve",
    data: BytesLike
  ): Result;
}

export namespace NameRegisteredEvent {
  export type InputTuple = [
    indexedName: string,
    name: string,
    agentId: BigNumberish,
    owner: AddressLike
  ];
  export type OutputTuple = [
    indexedName: string,
    name: string,
    agentId: bigint,
    owner: string
  ];
  export interface OutputObject {
    indexedName: string;
    name: string;
    agentId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NameReleasedEvent {
  export type InputTuple = [
    indexedName: string,
    name: string,
    agentId: BigNumberish
  ];
  export type OutputTuple = [
    indexedName: string,
    name: string,
    agentId: bigint
  ];
  export interface OutputObject {
    indexedName: string;
    name: string;
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TempoNameService extends BaseContract {
  connect(runner?: ContractRunner | null): TempoNameService;
  waitForDeployment(): Promise<this>;

  interface: TempoNameServiceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentIdToName: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  isNameAvailable: TypedContractMethod<[name: string], [boolean], "view">;

  nameToAgentId: TypedContractMethod<[arg0: string], [bigint], "view">;

  registerName: TypedContractMethod<
    [name: string, agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  releaseName: TypedContractMethod<[name: string], [void], "nonpayable">;

  resolveName: TypedContractMethod<[name: string], [bigint], "view">;

  resolveOwner: TypedContractMethod<[name: string], [string], "view">;

  reverseResolve: TypedContractMethod<
    [agentId: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentIdToName"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isNameAvailable"
  ): TypedContractMethod<[name: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "nameToAgentId"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerName"
  ): TypedContractMethod<
    [name: string, agentId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseName"
  ): TypedContractMethod<[name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveName"
  ): TypedContractMethod<[name: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "resolveOwner"
  ): TypedContractMethod<[name: string], [string], "view">;
  getFunction(
    nameOrSignature: "reverseResolve"
  ): TypedContractMethod<[agentId: BigNumberish], [string], "view">;

  getEvent(
    key: "NameRegistered"
  ): TypedContractEvent<
    NameRegisteredEvent.InputTuple,
    NameRegisteredEvent.OutputTuple,
    NameRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "NameReleased"
  ): TypedContractEvent<
    NameReleasedEvent.InputTuple,
    NameReleasedEvent.OutputTuple,
    NameReleasedEvent.OutputObject
  >;

  filters: {
    "NameRegistered(string,string,uint256,address)": TypedContractEvent<
      NameRegisteredEvent.InputTuple,
      NameRegisteredEvent.OutputTuple,
      NameRegisteredEvent.OutputObject
    >;
    NameRegistered: TypedContractEvent<
      NameRegisteredEvent.InputTuple,
      NameRegisteredEvent.OutputTuple,
      NameRegisteredEvent.OutputObject
    >;

    "NameReleased(string,string,uint256)": TypedContractEvent<
      NameReleasedEvent.InputTuple,
      NameReleasedEvent.OutputTuple,
      NameReleasedEvent.OutputObject
    >;
    NameReleased: TypedContractEvent<
      NameReleasedEvent.InputTuple,
      NameReleasedEvent.OutputTuple,
      NameReleasedEvent.OutputObject
    >;
  };
}
