/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TempoIdentityRegistry__factory } from "./TempoIdentityRegistry__factory";
export { TempoNameService__factory } from "./TempoNameService__factory";
export { TempoReputationRegistry__factory } from "./TempoReputationRegistry__factory";
